require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

RSpec/MultipleMemoizedHelpers:
  Max: 10

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 150

Metrics/ModuleLength:
  Max: 200

Metrics/AbcSize:
  Max: 70
